using System.Collections;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using Core.Contracts.Shared;

namespace UI.Transition
{
    /// <summary>
    /// Quản lý hiệu ứng màn hình đen khi ngủ. Triển khai ITransitionService để dễ dàng thay thế sau này.
    /// </summary>
    public class SleepTransitionUI : MonoBehaviour, ITransitionService
    {
        public static SleepTransitionUI Instance { get; private set; }

        [Header("UI References")]
        [SerializeField] private CanvasGroup blackOverlay;
        [SerializeField] private TextMeshProUGUI statusText;

        public bool IsTransitioning { get; private set; }

        public static void EnsureInstance()
        {
            if (Instance != null) return;

            GameObject root = new GameObject("SleepTransitionUI_AutoGenerated");
            var canvas = root.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvas.sortingOrder = 999;
            root.AddComponent<CanvasScaler>();
            root.AddComponent<GraphicRaycaster>();
            
            var groupObj = new GameObject("Overlay");
            groupObj.transform.SetParent(root.transform);
            var rect = groupObj.AddComponent<RectTransform>();
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.sizeDelta = Vector2.zero;
            
            var image = groupObj.AddComponent<Image>();
            image.color = Color.black;
            var group = groupObj.AddComponent<CanvasGroup>();
            
            var textObj = new GameObject("StatusText");
            textObj.transform.SetParent(groupObj.transform);
            var textRect = textObj.AddComponent<RectTransform>();
            textRect.anchorMin = new Vector2(0.5f, 0.4f);
            textRect.anchorMax = new Vector2(0.5f, 0.4f);
            textRect.sizeDelta = new Vector2(400, 100);
            
            var tmp = textObj.AddComponent<TextMeshProUGUI>();
            tmp.text = "Đang nghỉ ngơi...";
            tmp.alignment = TextAlignmentOptions.Center;
            tmp.fontSize = 36;
            tmp.color = Color.white;

            var script = root.AddComponent<SleepTransitionUI>();
            script.blackOverlay = group;
            script.statusText = tmp;
            
            DontDestroyOnLoad(root);
        }

        private void Awake()
        {
            if (Instance != null)
            {
                Destroy(gameObject);
                return;
            }
            Instance = this;
            
            if (blackOverlay != null)
            {
                blackOverlay.alpha = 0;
                blackOverlay.gameObject.SetActive(false);
            }
        }

        public IEnumerator FadeOut(float duration, string status = "Đang nghỉ ngơi...")
        {
            if (blackOverlay == null) yield break;

            IsTransitioning = true;
            blackOverlay.gameObject.SetActive(true);
            if (statusText != null) statusText.text = status;

            float timer = 0;
            while (timer < duration)
            {
                // Sử dụng unscaledDeltaTime để chạy xuyên qua Pause
                timer += Time.unscaledDeltaTime;
                blackOverlay.alpha = Mathf.Lerp(0, 1, timer / duration);
                yield return null;
            }
            blackOverlay.alpha = 1;
        }

        public IEnumerator FadeIn(float duration)
        {
            if (blackOverlay == null) yield break;

            float timer = 0;
            while (timer < duration)
            {
                timer += Time.unscaledDeltaTime;
                blackOverlay.alpha = Mathf.Lerp(1, 0, timer / duration);
                yield return null;
            }
            blackOverlay.alpha = 0;
            blackOverlay.gameObject.SetActive(false);
            IsTransitioning = false;
        }

        // Tương thích với code cũ (nếu có)
        public IEnumerator FadeOutRoutine(float d, string s) => FadeOut(d, s);
        public IEnumerator FadeInRoutine(float d) => FadeIn(d);
    }
}
